### ISSUE TITLE
A open source Chinese TTS software: eGuideDog

### ISSUE THREAD

**Issue by chevalun** [tinyfool/ChineseWithEnglish#1]
I've been looking for open source Chinese TTS software for a while, and ended up with eGuideDog project.
It works on my mac, though its pronunciation quality cannot compare with those commercial alternatives.
See http://www.eguidedog.net/ for details.

**Comment by tinyfool** [comment]
谢谢，不过这个项目主要为了有趣，还是会继续做的。
